version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
matrix:
  include:
    - node_js: "12.16.0" # this node version incorrectly shows the experimental warning
      env: TEST=true
